Improve array iterator
arangodb/java-velocypack pull request #19
Opened 2020-03-23 13:55 UTC by mpoeter

For compact arrays, the old implementation was quadratic, resulting in absolutely terrible performance for large arrays.

2020-03-24 14:20 UTC, rashtao requested changes
Thanks for your contribution, but the code as is does not compile. Please check my suggestions...

2020-03-24 14:20 UTC, rashtao commented on src/main/java/com/arangodb/velocypack/VPack.java
> +        for (final Iterator<VPackSlice> iterator = vpack.arrayIterator(); iterator.hasNext(); ) {
```suggestion
        int i = 0;
        for (final Iterator<VPackSlice> iterator = vpack.arrayIterator(); iterator.hasNext(); ) {
```

2020-03-24 14:20 UTC, rashtao commented on src/main/java/com/arangodb/velocypack/VPack.java
> +            Array.set(value, i, getValue(parent, iterator.next(), componentType, null));
```suggestion
            Array.set(value, i++, getValue(parent, iterator.next(), componentType, null));
```

2020-03-24 14:58 UTC, mpoeter commented
You are right, sorry! Seems like the IDE did not pick up my latest changes for my last test run before committing. Should be fixed now.

2020-03-24 15:17 UTC, rashtao approved these changes

2020-03-24 15:18 UTC, merged

2020-03-24 15:42 UTC, mpoeter commented
Thanks! Do you have an ETA for a new release that contains this fix?

2020-03-25 09:57 UTC, rashtao commented
@mpoeter releasing now... Thanks again!